/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.tsolval.testbed

import java.util.Arrays;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
class App {

    static void main(String[] args) {
        SpringApplication.run(App.class, args)
    }
}
